### ISSUE TITLE
add the terms to the auto-tag workflow

### ISSUE THREAD

**Issue by cfhaak** [NestroyCA/data#1]
there are lists with lemmas etc

**Comment by cfhaak** [comment]
@ckatsikadeli 
seems to work, but I match only a realy small amount
Is this what you expected?

**Comment by ckatsikadeli** [comment]
Yes, indeed. Besides the NE-tagging is more important. I'll try to increase the terms sample in the following days, but it will definitely be less successful than the NE.

**Comment by cfhaak** [comment]
Thanks, just wanted to make shure, that the script was working properly!
